# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Plus62store
email: your-email@example.com
avatar: https://1.bp.blogspot.com/-1bWHHqO2Jt0/X2ZgjgIVRVI/AAAAAAAAFZ8/XCb6roqGxhIn-K34II1L8BuLDoAePrmsgCLcBGAsYHQ/s0/192x192.png
description: Jual Masker Bordir Tasikmalaya..
baseurl: "" 
url: "https://plus62store.my.id"
twitter_username: x1666
github_username:  7897git
sitekey: 6LdPL-wZAAAAAAzUvjEWXHGLAgKL78wBzB1IR8t7
fb-pixel: 791401205101923
fb-appID: 437300347340287
fb-admin: 158878762428839
fb-profile: 435671100899312
fb-pages: 107881477662203
signal-id: 6d1eb5cd-8c5d-4cf3-aa06-eed9c3e1aee0
safari-web-ID: web.onesignal.auto.0f4ef0fc-d020-4184-9066-253532c318fc
G-verify:
comen: 30234

# Build settings
plugins:
  - jekyll-feed

collections:
  product:
    output: true
  blog:
    output: true

permalink: /:title

defaults:
- scope:
    type: product
  values:
    layout: shop

- scope:
    type: checkout
  values:
    layout: checkout-page

- scope:
    type: cart
  values:
    layout: cart-page

- scope:
    type: pages
  values:
    layout: page

- scope:
    type: blog
  values:
    layout: post

compress_html:
  clippings: all
  ignore:
    envs: development

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
